### ISSUE TITLE
How about adding search to the documentations part of the website?

### ISSUE THREAD

**Issue by tobiasbueschel** [espanso/website#7]
Hi Espanso team,

I really like the website and documentation, great work! I noticed that search is missing - have you already considered adding it using: https://docusaurus.io/docs/search?

Cheers

**Comment by federico-terzi** [comment]
Hey @tobiasbueschel,

Thank you for the feedback! You're definitely right, I'll investigate :)

Cheers :)

**Comment by tobiasbueschel** [comment]
Sounds good 😊 By the way, there's also a static version of search for Docusaurus: https://github.com/cmfcmf/docusaurus-search-local if Algolia or a self-hosted version is not an option.

**Comment by protiumx** [comment]
Hi!
I was just looking into this, I tried some of the plugins for local search but all of them are breaking the build.
I guess the best option is Algolia since it's free for open source projects, the owner of the repo must apply tho: https://docsearch.algolia.com/apply/

**Comment by federico-terzi** [comment]
A bit late, but now the Docs have a search feature :) Used Algolia as suggested by @protiumx

**Comment by tobiasbueschel** [comment]
that's awesome, thanks @federico-terzi 👏
